trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group : AZ

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
  displayName: 'Azure Login'

- script: |
    az vmss list-instances --resource-group $(resourceGroupName) --name $(vmssName) --query "[].{id:id, instanceId:instanceId, name:name}" --output table
  displayName: 'List VMSS Instances'

- script: |
    instanceIp=$(az vmss list-instance-public-ips --resource-group $(resourceGroupName) --name $(vmssName) --query "[?instanceId=='$(instanceId)'].ipAddress" --output tsv)
    echo "Instance IP: $instanceIp"
  displayName: 'Get Instance IP'

