trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  VMSS_NAME: 'GiftsCenterVMSS'
  RESOURCE_GROUP: 'ikascoRG'
  ADMIN_USERNAME: 'IKASCOAdmin'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ikascoConn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get instance IDs
      instance_ids=$(az vmss list-instances --resource-group $(RESOURCE_GROUP) --name $(VMSS_NAME) --query "[].instanceId" -o tsv)
      # Install dependencies on each VMSS instance
      for instance_id in $instance_ids; do
      echo "setup instance $instance_id"
        az vmss run-command invoke \
          --resource-group $(RESOURCE_GROUP) \
          --name $(VMSS_NAME) \
          --command-id RunShellScript \
          --instance-id $instance_id \
          --scripts "
            sudo apt update &&
            sudo apt install -y git nginx php php-fpm php-mysql unzip &&
            sudo mkdir -p /var/www/html/gc &&
            sudo chown -R IKASCOAdmin:IKASCOAdmin /var/www/html/gc &&
            sudo chmod -R 755 /var/www/html/gc
          "
      done

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ikascoConn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get instance IDs
      instance_ids=$(az vmss list-instances --resource-group $(RESOURCE_GROUP) --name $(VMSS_NAME) --query "[].instanceId" -o tsv)

      # Clone repository on each VMSS instance
      for instance_id in $instance_ids; do
        az vmss run-command invoke \
          --resource-group $(RESOURCE_GROUP) \
          --name $(VMSS_NAME) \
          --command-id RunShellScript \
          --instance-id $instance_id \
          --scripts "
            cd /var/www/html/gc &&
            sudo git clone https://9dByNAOPJmNVnt0KWjqCBWa2gDRrd8EUdKhnFjUIaDnBqfytL6V1JQQJ99AKACAAAAAhxyoqAAASAZDO4JX9@dev.azure.com/IKASCO/Website/_git/Website . &&
            sudo composer install
          "
      done

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ikascoConn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get instance IDs
      instance_ids=$(az vmss list-instances --resource-group $(RESOURCE_GROUP) --name $(VMSS_NAME) --query "[].instanceId" -o tsv)

      # Configure Nginx on each VMSS instance
      for instance_id in $instance_ids; do
        az vmss run-command invoke \
          --resource-group $(RESOURCE_GROUP) \
          --name $(VMSS_NAME) \
          --command-id RunShellScript \
          --instance-id $instance_id \
          --scripts "
            echo 'server {
                listen 80;
                server_name taraf-jo.com www.taraf-jo.com;
                root /var/www/html/gc;
                index index.php index.html;
                
                location / {
                    try_files \$uri \$uri/ /index.php?\$query_string;
                }
                
                location ~ \.php$ {
                    include snippets/fastcgi-php.conf;
                    fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
                }
            }' | sudo tee /etc/nginx/sites-available/gc

            sudo ln -s /etc/nginx/sites-available/gc /etc/nginx/sites-enabled/
            sudo systemctl restart nginx
          "
      done
