trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '**/*.zip'
    destinationFolder: ''
    cleanDestinationFolder: true
    overwriteExistingFiles: false