trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  VMSS_NAME: 'GCVMSS'
  RESOURCE_GROUP: 'ikascoRG'
  ADMIN_USERNAME: 'IKASCOAdmin'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

inputs:
    azureSubscription: 'ikascoConn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get instance IDs
      instance_ids=$(az vmss list-instances --resource-group $(RESOURCE_GROUP) --name $(VMSS_NAME) --query "[].instanceId" -o tsv)

      # Update repository on each VMSS instance
      for instance_id in $instance_ids; do
        az vmss run-command invoke \
          --resource-group $(RESOURCE_GROUP) \
          --name $(VMSS_NAME) \
          --command-id RunShellScript \
          --instance-id $instance_id \
          --scripts "
            cd /var/www/html/gc || exit
            sudo git pull origin main
          "
          done