trigger:
  branches:
    include:
      - main  # Change this to your branch name

pool:
  vmImage: 'ubuntu-latest'  # Use an appropriate VM image

variables:
  resourceGroupName: 'ikascoRG'
  vmssName: 'GiftsCenterVMSS'
  instanceId: '87'  # Specify which instance to deploy to

stages:
- stage: Deploy
  jobs:
  - job: DeployToVMSS
    steps:
    - checkout: self

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'ikascoConn'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az vmss update-instances --resource-group $(resourceGroupName) --name $(vmssName) --instance-ids $(instanceId)
          
          # Download the ZIP file from the build artifacts
          curl -o /var/www/html/$(Build.BuildId).zip "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
          
          # Unzip the file
          unzip /var/www/html/$(Build.BuildId).zip -d /var/www/html
          
          # Set the correct permissions
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html
