trigger:
  branches:
    include:
      - main  # Adjust as needed

pool:
  vmImage: 'ubuntu-latest'  # or windows-latest if you're using Windows agents

variables:
  azureSubscription: 'ikasco Subscription'
  resourceGroupName: 'dbIKASCO'
  scaleSetName: 'GiftsCenter'
  StorageAccountName: 'ikascostorage'
  ContainerName: 'deploys'

steps:
#- checkout: self  # Check out the current repository

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureFileCopy@6
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    azureSubscription: 'ikascoConn'
    Destination: 'AzureVMs'
    storage: 'ikascostorage'
    resourceGroup: 'DBIKASCO'
    vmsAdminUserName: 'IKASCOAdmin'
    vmsAdminPassword: 'YOmopbAX6BqoV8voVtF0'
    TargetPath: '/var/www/html/'