trigger:
  branches:
    include:
      - main  # Adjust as needed

pool:
  vmImage: 'ubuntu-latest'  # or windows-latest if you're using Windows agents

variables:
  azureSubscription: 'ikascoConn'
  resourceGroupName: 'ikascoRG'
  scaleSetName: 'GiftsCenterVMSS'
  StorageAccountName: 'ikascostorage'
  ContainerName: 'deploys'

steps:
#- checkout: self  # Check out the current repository

- script: |
    echo "Listing files in $(Build.SourcesDirectory)"
    ls -R $(Build.SourcesDirectory)  # List files recursively
  displayName: 'List source directory'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureCLI@2
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get the list of VM instances in the scale set
      vmssInstances=$(az vmss list-instances --resource-group $(resourceGroupName) --name $(scaleSetName) --query "[].id" -o tsv)
      
      # Loop through each VM instance and upload the file
      for vm in $vmssInstances; do
        az vm run-command invoke --ids $vm --command-id RunShellScript --scripts "mkdir -p /var/www/html/web && unzip -o /var/www/html/$(Build.BuildId).zip -d /var/www/html/web && chmod -R 777 /var/www/html/web" --parameters "zipFile=$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      done
    addSpnToEnvironment: true
