trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  VMSS_NAME: 'GCVMSS'
  RESOURCE_GROUP: 'ikascoRG'
  ADMIN_USERNAME: 'IKASCOAdmin'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ikascoConn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get instance IDs
      instance_ids=$(az vmss list-instances --resource-group $(RESOURCE_GROUP) --name $(VMSS_NAME) --query "[].instanceId" -o tsv)
      # Install dependencies on each VMSS instance
      for instance_id in $instance_ids; do
      echo "setup instance $instance_id"
        az vmss run-command invoke \
          --resource-group $(RESOURCE_GROUP) \
          --name $(VMSS_NAME) \
          --command-id RunShellScript \
          --instance-id $instance_id \
          --scripts "
            sudo apt update &&
            sudo apt install -y git nginx php-fpm php-mysql php-xml php-gd unzip composer &&
            sudo mkdir -p /var/www/html/gc &&
            sudo chown -R IKASCOAdmin:IKASCOAdmin /var/www/html/gc &&
            sudo chmod -R 755 /var/www/html/gc
          "
      done

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ikascoConn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get instance IDs
      instance_ids=$(az vmss list-instances --resource-group $(RESOURCE_GROUP) --name $(VMSS_NAME) --query "[].instanceId" -o tsv)

      # Clone repository on each VMSS instance
      for instance_id in $instance_ids; do
        az vmss run-command invoke \
          --resource-group $(RESOURCE_GROUP) \
          --name $(VMSS_NAME) \
          --command-id RunShellScript \
          --instance-id $instance_id \
          --scripts "
            export COMPOSER_HOME=/var/www/.composer &&
            cd /var/www/html/gc &&
            sudo git clone https://9dByNAOPJmNVnt0KWjqCBWa2gDRrd8EUdKhnFjUIaDnBqfytL6V1JQQJ99AKACAAAAAhxyoqAAASAZDO4JX9@dev.azure.com/IKASCO/Website/_git/Website . &&
            sudo chown -R IKASCOAdmin:IKASCOAdmin /var/www/html/gc &&
            sudo chmod -R 755 /var/www/html/gc && 
            sudo -u IKASCOAdmin -H sh -c 'composer update' &&
            sudo chmod -R 777 /var/www/html/gc/storage  &&
            cd /var/www/html/gc/watches.giftscenter.com &&
            sudo -u IKASCOAdmin -H sh -c 'composer update' &&
            sudo chmod -R 777 /var/www/html/gc/watches.giftscenter.com/storage
          "
      done

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ikascoConn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get instance IDs
      instance_ids=$(az vmss list-instances --resource-group $(RESOURCE_GROUP) --name $(VMSS_NAME) --query "[].instanceId" -o tsv)

      # Configure Nginx on each VMSS instance
      for instance_id in $instance_ids; do
        az vmss run-command invoke \
          --resource-group $(RESOURCE_GROUP) \
          --name $(VMSS_NAME) \
          --command-id RunShellScript \
          --instance-id $instance_id \
          --scripts "
            sudo cp /var/www/html/gc/SSL/gc_crt.crt /etc/ssl/certs/ &&
            sudo cp /var/www/html/gc/SSL/gc_private.key /etc/ssl/private/ &&
            sudo cp /var/www/html/gc/SSL/gc_bundle.crt /etc/ssl/certs/ &&
            sudo cp /var/www/html/gc/SSL/GCssl /etc/nginx/sites-available/ &&
            sudo ln -s /etc/nginx/sites-available/GCssl /etc/nginx/sites-enabled/
            sudo systemctl restart nginx
          "
      done
