trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  VMSS_NAME: 'GCVMSS'
  RESOURCE_GROUP: 'ikascoRG'
  ADMIN_USERNAME: 'IKASCOAdmin'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ikascoConn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get instance IDs
      instance_ids=$(az vmss list-instances --resource-group $(RESOURCE_GROUP) --name $(VMSS_NAME) --query "[].instanceId" -o tsv)

      # Update repository on each VMSS instance
      for instance_id in $instance_ids; do
        az vmss run-command invoke \
          --resource-group $(RESOURCE_GROUP) \
          --name $(VMSS_NAME) \
          --command-id RunShellScript \
          --instance-id $instance_id \
          --scripts "
            cd /var/www/html/gc || exit
            sudo -u IKASCOAdmin git config --global --add safe.directory /var/www/html/gc
            sudo -u IKASCOAdmin git pull origin main
          
            # Check if Composer is installed
            if ! command -v composer &> /dev/null
            then
              echo 'Composer not found, installing...'
              curl -sS https://getcomposer.org/installer | php
              sudo mv composer.phar /usr/local/bin/composer
            fi

            # Install Composer dependencies
            sudo -u IKASCOAdmin composer install --no-dev --optimize-autoloader"
      done
