<?php

namespace Modules\Order\Entities;

use Illuminate\Database\Eloquent\Model;

class SalePos extends Model
{
    protected $table = 'sales_table_item_pos';


    protected $fillable = [
        'sales_id',
        'product_id',
        'product_no',
        'title',
        'category',
        'tax',
        'discount',
        'qty',
        'rec_qty',
        'adv',
        'retail_price',
        'wholesale_price',
        'total',
        'sales_person',
        'sales_person_id',
        'store_id',
        'company_id',
        'acc_no',
        'acc_id',
        'location',
        'brand',
        'supplier',
        'post',
        'brand_id',
        'supplier_id',
        'brand_code',
        'supp_code',
        'posted_date',
        'barcode',
        'ref_no',
        'sub_store',
        'chain_id',
        'transaction_no',
        'type',
        'main_cat_id',
        'division',
        'distributor',
        'payment_type',
        'status',
        'card_no',
        'card_type',
        'cat_id',
        'sub_cat_id',
        'func_flag',
        'sale_date_time',
        'sale_date',
        'discount_price',
        'tax_price',
        'from_company',
        'old_invoice',
        'unit_price_wot',
        'unit_price_wt',
        'Custmr_Dscnt',
        'Custmr_Dscnt_Value',
        'Invest',
        'Invest_Disc_Value_WT',
        'Extra_Dscn_per',
        'Extra_Dscnt_Value_WT',
        'Notes',
        'posting_date',
        'store_manager',
        'customer_name',
        'customer_no',
        'new_status',
        'consignment',
        'rand_pur',
        'phone',
        'tax_free',
        'all_update',
        'sub_invoice',
        'pos_cust',
        'pos_phone',
        'updatedphone',
        'customer_no_1',
        'customer_name_1',
        'checks',
        'delphone',
        'delivery_status',
        'Webform',
        'cc',
        'whole2',
        'online',
        'offer',
        'loyalty',
        'posted_invoice',
        'old_category',
        'wraps',
        'point_discount',
        'point_discount_price',
        'time',
        'store_no',
        'live',
        'live_gr',
        'times',
        'live_pos',
        'sales_type',
        'note',
        'customer_date',
        'shipping_charge',
        'coupon_discount',
        'coupon_code',
        'patch',
        'redeemed_amount',
        'bundle',
        'Employee_id'
    ];


}